### ISSUE TITLE
Not supporting IPV6 address

### ISSUE THREAD

**Issue by biozzl** [imajeason/nas_tools#4]
2022/11/03 22:59:34 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /opt/caddy -ldflags -w -s -trimpath 
2022/11/03 23:03:20 [INFO] Build complete: ./caddy
2022/11/03 23:03:20 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-11-03-2258.1723510728
v2.6.2 h1:wKoFIxpmOJLGl3QXoo6PNbYvGW4xLEgo32GPBEjWL8o=
mkdir: cannot create directory ‘/etc/caddy/’: File exists
ls: cannot access '/etc/letsencrypt/live/': No such file or directory
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Requesting a certificate for xxxx.ipv6a.my.id
Performing the following challenges:
http-01 challenge for xxxx.ipv6a.my.id
Waiting for verification...
Challenge failed for domain xxxx.ipv6a.my.id
http-01 challenge for xxxx.ipv6a.my.id
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: dustpower.ipv6a.my.id
   Type:   tls
   Detail: 2001:xxxx:203:698:xxxx:1234:5f4c:1: Fetching
   https://xxxx.ipv6a.my.id/.well-known/acme-challenge/bbgMimqRowpfox6zNTiRYXlxd3TwLizZezkogGtcHNc:
   remote error: tls: internal error

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   you have an up-to-date TLS configuration that allows the server to
   communicate with the Certbot client.

**Comment by imajeason** [comment]
if your domain is ipv6,please make a AAAA record(s) for that domain.
until the dns is ok,installation wont continue.
